apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gcp-stackdriver-logging
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      name: gcp-stackdriver-logging
  template:
    metadata:
      labels:
        name: gcp-stackdriver-logging
    spec:
      volumes:
        # Este volumen se destruira cuando el pod se destruya tambien. Es lo buscado.
        - name: data-volume
          emptyDir: {}
        # Volumen para almacenar el token de GCP
        - name: google-cloud-key
          secret:
            secretName: log-extractor
      containers:
        - image: circulo7/gcp-stackdriver-logging:0.0.1
          name: gcp-stackdriver-logging
          imagePullPolicy: Always
          volumeMounts:
            - name: data-volume
              mountPath: /opt/gcp-log-extractor/
            - name: google-cloud-key
              mountPath: /var/secrets/google
          resources:
            limits:
              memory: "320Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 80
            periodSeconds: 20
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 80
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: STACKDRIVER_LOG_NAME
              value: gcp-stackdriver-logging
            - name: LOG_FLUSH_LEVEL
              value: INFO
            - name: LOGEXTRACTORBASEDIR
              value: ""
            - name: SPRING_MAIL_HOST
              value: ""
            - name: SPRING_MAIL_PORT
              value: "587"
            - name: SPRING_MAIL_USERNAME
              value: ""
            - name: SPRING_MAIL_PASSWORD
              value: ""
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
              value: "true"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
              value: "true"
